Update ta-maxlength.js
Resolve the 

```
vendor.1520808592048.js:1 Error: [$injector:unpr] Unknown provider: eProvider <- e <- taMaxlengthDirective
http://errors.angularjs.org/1.6.9/$injector/unpr?p0=eProvider%20%3C-%20e%20%3C-%20taMaxlengthDirective
    at vendor.1520808592048.js:1
    at vendor.1520808592048.js:1
    at Object.a [as get] (vendor.1520808592048.js:1)
    at vendor.1520808592048.js:1
    at a (vendor.1520808592048.js:1)
    at l (vendor.1520808592048.js:1)
    at Object.invoke (vendor.1520808592048.js:1)
    at vendor.1520808592048.js:1
    at x (vendor.1520808592048.js:1)
    at Object.<anonymous> (vendor.1520808592048.js:1)
```

error due to minification